### PR TITLE
fix(images): Tidying up the AMI config for windows to reduce some duplication

### PR DESCRIPTION
**Pull request by ScottGuymer**
While implementing a windows AMI I noticed some duplication that can be removed, and some scripting aligned more with the Linux example.

### CODE REVIEW

**Review by npalm — COMMENTED** [review]
LGTM, tested building the AMI. Got the following warning:

```
    githubactions-runner.amazon-ebs.githubrunner: WARNING: Can't find git.install install location
    githubactions-runner.amazon-ebs.githubrunner:   git.install can be automatically uninstalled.
    
 ```
 
 Could this cause a problem?

**Comment by npalm** [comment]
As part of this PR can you also make a small update to the README for images, and mention the windows example?

**Review by npalm — APPROVED** [review]

**Comment by ScottGuymer** [comment]
> LGTM, tested building the AMI. Got the following warning:
> 
> ```
>     githubactions-runner.amazon-ebs.githubrunner: WARNING: Can't find git.install install location
>     githubactions-runner.amazon-ebs.githubrunner:   git.install can be automatically uninstalled.
>     
> ```
> 
> Could this cause a problem?

Seems like an odd warning but doesnt indicate git was not installed so its probably nothing.

**Comment by npalm** [comment]
@ScottGuymer what is the status of this PR?

**Comment by ScottGuymer** [comment]
I had not got around to testing this fully yet

**Comment by npalm** [comment]
> I had not got around to testing this fully yet

thx for the update

**Pull request closed without merging**
